# Site settings
title: Akupunkturpraktiken
email: bittan_wallin@hotmail.com
description: Akupunkturpraktiken i Tidaholm och Göteborg
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.akupunkturpraktikenvast.se" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 5

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
